# Generated by Django 3.0.8 on 2020-07-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyhome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date_posted',
            new_name='date_published',
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='view',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
