# Generated by Django 3.0.8 on 2020-07-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyhome', '0002_auto_20200716_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.TextField(default=None),
        ),
    ]
